string desired_frame
---
bool red_present
bool blue_present
bool yellow_present
bool green_present
geometry_msgs/PointStamped[] red_points
geometry_msgs/PointStamped[] blue_points 
geometry_msgs/PointStamped[] yellow_points
geometry_msgs/PointStamped[] green_points
